### ISSUE TITLE
Fast Neural Style

### ISSUE THREAD

**Issue by GlebSBrykin** [mashmawy/ConvNetCS#1]
Hello! Why not implement in C# a quick algorithm to the styling of the images? At the moment there are many implementations, in addition to C#. Here are a few examples:
In JavaScript: https://github.com/reiinakano/fast-style-transfer-deeplearnjs
In TensorFlow: https://github.com/lengstrom/fast-style-transfer
In Torch7: https://github.com/jcjohnson/fast-neural-style
I believe the C# implementation will be a major breakthrough!

**Comment by mashmawy** [comment]
nice
I'll work on it

**Comment by GlebSBrykin** [comment]
Hello! Thank you very much for your answer.
[https://github.com/reiinakano/fast-style-transfer-deeplearnjs](https://github.com/reiinakano/fast-style-transfer-deeplearnjs) - this repository contains ready-made models for several styles in the lightest format, JavaScript code. It uses the architecture of the most efficient neural network. I think the implementation of this project will be the easiest and most effective. This implementation is closest to C#.
In General, as I see, more than 50% of your projects have already been implemented.
Thank You! Looking forward to the news!

**Comment by mashmawy** [comment]
I'm still working on it. I'll do it.

**Comment by GlebSBrykin** [comment]
Hello! I'm sorry to have so many premature questions, but let me ask you one more. When training a neural network for fast styling, Leon Gatis's "A neural algorithm of artistic style" algorithm is always used. So, will it be possible to use this algorithm not only for network training, but also for styling  images itself? I think this opportunity is very useful.

**Comment by mashmawy** [comment]
yes, the same algorithm is used.
correct me if i'm wrong, in training we extract style filters and apply it to generated white image.

**Comment by GlebSBrykin** [comment]
I understand you're right. I mean it is an algorithm Gatis. I think you will understand more about his article: 
[https://arxiv.org/pdf/1508.06576](https://arxiv.org/pdf/1508.06576).
I found another article, but it's in Russian: [https://m.habr.com/company/mailru/blog/306916/](https://m.habr.com/company/mailru/blog/306916/). In my opinion, the Gatis algorithm gives more beautiful results than the pre-trained network. In addition, it will be much easier to implement, because you have a trained network of VGG-16 in C# and optimizers. I can see an example of the work on the page of one of the implementations of the algorithm:[https://github.com/ckmarkoh/neuralart_tensorflow](https://github.com/ckmarkoh/neuralart_tensorflow).

**Comment by GlebSBrykin** [comment]
I think it's better to start with this. By the way, it is quite possible to execute as an example to ConvNetCS! To make it easier to compare, here's an example result with a quick style and Algorithm from Gatis.
Result from Gatis:
![taipei101_starrynight](https://user-images.githubusercontent.com/36363358/40468454-c6016944-5f2d-11e8-8e6c-12dbc6ee5753.jpg)
Result from the best fast neural style network by Justin Johnson:
![chicago_starry_night](https://user-images.githubusercontent.com/36363358/40468507-e84c6d00-5f2d-11e8-8e1b-6587d5adfcef.jpg)
I think the difference is obvious.
I hope you manage to do it! Good luck!

**Comment by mashmawy** [comment]
i already implemented the algorithm and run the pretrained model successfully, I'll upload it soon after cleaning the code and optimize the ops to be more fast.

**Comment by mashmawy** [comment]
I'm porting tensorflowjs to c# for this. its more challenging and more fun

**Comment by GlebSBrykin** [comment]
Great! Greetings! But there are only 6 styles. Will you make it possible to generate styles? Is Your mail listed here now valid? I also managed to port models and could send my implementation. It is written on PascalABC.NET and less efficient than Yours, has no possibility of generation styles, but may be of interest to You. Would you mind if I post it on my GitHub page?

**Comment by GlebSBrykin** [comment]
I should note that you managed to implement the styling much faster than me, 3 times faster!

**Comment by mashmawy** [comment]
here you go https://github.com/mashmawy/albiruni
this is albiruni library it is a c# fork of tensorflowjs "core" along with fast style transfer .
it has an expermintal gpu backend and the library is in early stage.
your contribution is more than welcome.
i updated my email.
