### ISSUE TITLE
Porting the model of a neural network from Caffe to ConvNetCS.

### ISSUE THREAD

**Issue by Gleb845** [mashmawy/ConvNetCS#2]
Hi! Recently, I became interested in neural networks due to the discovery of a service, that allows you to automatically paint pictures. Having studied materials a little, I found out, that the network is written on Caffe. Can you help me to rewrite this neural network for using in ConvNetCS? You've managed to port the model VGG16! You can find this network here: [https://github.com/richzhang/colorization](https://github.com/richzhang/colorization)

**Comment by mashmawy** [comment]
I'm currently working on fast style transfer.

**Comment by GlebSBrykin** [comment]
A good idea, maybe you will take up the implementation? By the way, why did you delete Albiruni?

**Comment by mashmawy** [comment]
yes it's a good idea.
Albiruni will be re-uploaded soon.
