### ISSUE TITLE
A neural algorithm of artistic style and 2 new layers for ConvNetCS

### ISSUE THREAD

**Issue by GlebSBrykin** [mashmawy/ConvNetCS#3]
Hello! I was able to implement two new layers for ConvNetCS. These layers AvgPoolLayer - layer averaging pooling and AvgUnpoolLayer - layer upsampling. Also I was able to implement the fragment algorithm Gatis for styling images - ContentLoss. It uses ConvNetCS and VGG16. I have problems with StyleLoss-style transfer. I suggest You implement the stylization algorithm Gatis. This would allow the training of a neural network for fast styling and styling images under any styles.

[Layers.zip](https://github.com/mashmawy/ConvNetCS/files/2077176/Layers.zip)

[ContentLoss.zip](https://github.com/mashmawy/ConvNetCS/files/2077200/ContentLoss.zip)

**Comment by mashmawy** [comment]
SORRY FOR THE LATE RESPONSE,
I JUST GOT MARRIED AND I WAS IN MY HONEYMOON
I WILL HAVE A LOOK

**Comment by GlebSBrykin** [comment]
Greetings!

**Comment by GlebSBrykin** [comment]
If you do this, please write in your old style like ConvNetCS. The code is really beautiful and clear, just like a tutorial!

**Comment by GlebSBrykin** [comment]
I've optimized the return pass through the convolution layer. It is now running in parallel. By the way, is there any progress in A neural algorithm of artistic style? 
[ConvLayer.zip](https://github.com/mashmawy/ConvNetCS/files/2232209/ConvLayer.zip)
I really hope That you will be able to implement this algorithm from Gatis.

**Comment by mashmawy** [comment]
implementing gatis in convnetcs will be hard and not reusable.
I'm trying to port a tensorflow like library that will help us to import any python tensorflow to c#.

**Comment by GlebSBrykin** [comment]
That's a good idea. I can only hope will be the start of prgoram on the CPU.

**Comment by GlebSBrykin** [comment]
I found some matherials about tensorflow on Windows: https://github.com/hartmutdavid/TensorFlow4Delphi. In this repository is precompiled TensorFlow(dll).

**Comment by GlebSBrykin** [comment]
Here is code in C#: https://github.com/migueldeicaza/TensorFlowSharp

**Comment by mashmawy** [comment]
looks good

**Comment by GlebSBrykin** [comment]
Do you have any results? I do not give up hope to implement the algorithm in pure C#. Here is already and texture repair.
![7fa4b9022a7bf11073fbe98f8fe749c13700fea6](https://user-images.githubusercontent.com/36363358/43635632-59b6f614-9718-11e8-8a72-0157c343137d.jpg)

**Comment by PABCSoft** [comment]
![7fa4b9022a7bf11073fbe98f8fe749c13700fea6](https://user-images.githubusercontent.com/36363358/43635649-6570f5e0-9718-11e8-8e27-04295fb6a7ce.jpg)

**Comment by GlebSBrykin** [comment]
AlbiruniML - amazing work! It's incredible! How long did you make it? Special thanks for CPU and clean and beautiful code! I was able to start styling using ConvNetCS.
![1](https://user-images.githubusercontent.com/36363358/43989348-d736e66a-9d50-11e8-8091-0da986d22210.jpg)
In the near future, I'll tell you all the details.

**Comment by mashmawy** [comment]
You did it , I will try to implement convnetcs based on AlbiruniML and add more layers.

**Comment by GlebSBrykin** [comment]
I have a proposal, more like a request. Can you implement the l-BFGS optimization algorithm(https://en.m.wikipedia.org/wiki/Limited-memory_BFGS)? It allows you to significantly speed up the generation of images and improve their appearance. Now I use Adam from ConvNetCS, which allowed me to improve the result compared to SGD many, many times. However, now to get a beautiful picture requires at least 50 iterations, and L-BFGS will reduce their number to 8. My knowledge does not allow me to do this on my own.

**Comment by mashmawy** [comment]
Accord.net has a very good L-BFGS optmizer, give it a try.
http://accord-framework.net/

**Comment by GlebSBrykin** [comment]
Looked interesting library, but it is very difficult to understand.

**Comment by GlebSBrykin** [comment]
Yesterday I generated another picture.
![img2](https://user-images.githubusercontent.com/36363358/44027690-0978c0c0-9f00-11e8-942e-a35f35a6de0a.jpg)

**Comment by GlebSBrykin** [comment]
I would still like to suggest you to implement L-BFGS optimizer for ConvNetCS and add it there. This is such a powerful method that it is difficult to imagine. And in Your performance as a part of ConvNetCS it will be clear to everyone.

**Comment by GlebSBrykin** [comment]
Will you be doing this?

**Comment by mashmawy** [comment]
I will write a new ConvNetCS version and i will try to implement L-BFGS in the new version.
L-BFGS need to compute all samples error first and the current ConvNetCS by nature do not support that "may be with workaround".

**Comment by GlebSBrykin** [comment]
I'll wait for the news. Now we have to build a bunch of bridges to use ConvNetCS for the Gatis algorithm.

**Comment by GlebSBrykin** [comment]
I keep experimenting. Here are the latest results.

![starry_night](https://user-images.githubusercontent.com/36363358/44708115-f4080d80-aaae-11e8-925a-f7de144f8673.png)
![seated_nude](https://user-images.githubusercontent.com/36363358/44708148-0eda8200-aaaf-11e8-9abc-e0a05ce14a3c.png)
![scream](https://user-images.githubusercontent.com/36363358/44708179-231e7f00-aaaf-11e8-86bf-f361e3d12400.png)

**Comment by mashmawy** [comment]
great job

**Comment by GlebSBrykin** [comment]
Do You have any results?

**Comment by mashmawy** [comment]
Not yet dear

**Comment by GlebSBrykin** [comment]
Posted my project: https://github.com/PABCSoft/NeuralArt

**Comment by mashmawy** [comment]
very nice

**Comment by GlebSBrykin** [comment]
Now I will add the English version.

**Comment by GlebSBrykin** [comment]
Here You can find the implementation in the English language: https://github.com/PABCSoft/NeuralArt/tree/English

**Comment by GlebSBrykin** [comment]
I'm looking for implementation options for L-BFGS-B and found some interesting repositories that can help You: https://github.com/stephenbeckr/L-BFGS-B-C , https://github.com/yejingxin/LBFGSB , https://github.com/afbarnard/go-lbfgsb
